[package]
name = "taitankrs"
description = "rust taitank"
version = "0.0.1-dev.0"
edition = "2021"
authors = ["meloalright", "rustq"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
